### PR TITLE
links search bar to pokemon details component

### PR DESCRIPTION
**Pull request by RyanBaer42**
## What does this merge do? Check all that apply.
- [x] Adds a new feature
- [x] Improves an existing feature
- [x] Fixes a bug
- [x] Cleans up (logs, tests, etc.)

## Description:
Links the search bar component to pokemon details. Pokemon details now display when a correctly spelled pokemon is submitted. 

## Issues:
The search bar still needs to be updated so that the state accurately matches whats is submitted in the form. 

## Where to find Changes:
Files: src/Components/PokemonDetails/PokemonDetails.tsx
Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have used tests to prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my change

### CODE REVIEW

**Review by crgweller — APPROVED** [review]
Great work, Ryan

**Review by derekgithub2 — COMMENTED** [review]
Great use of isLoading state to set a conditional to wait for the data to get back!

**Review by derekgithub2 — COMMENTED** [review]
Thanks for changing that filter!

**Review by KarimAl-Rashdan — APPROVED** [review]
Good job adding the html and loading to the page. Looks good.

**Pull request merged**
